name: 📸 Partager une Photo de Famille
description: Partagez vos photos préférées des célébrations d'anniversaire de Marine et Erwan !
title: "[PARTAGE PHOTO] "
labels: ["photo-upload", "pending-review"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🎉 Merci de partager vos souvenirs !

        Nous sommes ravis que vous souhaitiez contribuer des photos au site d'anniversaire de Marine et Erwan !

        **Comment ça marche :**
        1. Remplissez le formulaire ci-dessous
        2. Joignez vos photo(s) en les glissant-déposant dans la zone de description
        3. Soumettez l'issue
        4. Nous examinerons et ajouterons vos photos au site dans quelques jours !

        **OU envoyez directement par email à : marineeterwan29@gmail.com**

        ---

  - type: input
    id: contributor-name
    attributes:
      label: Votre Nom
      description: Qui partage ces merveilleuses photos ?
      placeholder: ex. Tante Sophie, Oncle Marc, Grand-mère Marie
    validations:
      required: true

  - type: dropdown
    id: photo-subject
    attributes:
      label: Qui est sur la/les photo(s) ?
      description: Sélectionnez le sujet principal de vos photos
      options:
        - Marine
        - Erwan
        - Marine et Erwan tous les deux
        - Photo de groupe familiale
        - Autres membres de la famille
    validations:
      required: true

  - type: textarea
    id: photo-description
    attributes:
      label: Description des Photos
      description: |
        Parlez-nous de ces photos ! Quelle est l'occasion ? Quand a-t-elle été prise ? Des souvenirs spéciaux ?

        **📎 GLISSEZ-DÉPOSEZ VOS PHOTOS ICI** (ou cliquez pour parcourir)

        Vous pouvez télécharger plusieurs photos à la fois. Formats supportés : JPG, PNG, GIF
      placeholder: |
        Exemple :
        "Ceci est de la fête d'anniversaire des 5 ans de Marine au parc. Elle a adoré le gâteau papillon !"

        [Glissez vos photos ici ou collez-les sous ce texte]
    validations:
      required: true

  - type: dropdown
    id: photo-occasion
    attributes:
      label: Occasion/Événement
      description: Quel type d'événement ou de moment cela capture-t-il ?
      options:
        - Célébration d'anniversaire
        - Réunion de famille
        - Fête de vacances
        - Moment quotidien
        - Étape importante
        - Autre
    validations:
      required: false

  - type: input
    id: photo-date
    attributes:
      label: Date Approximative
      description: Quand cette photo a-t-elle été prise ? (approximatif convient !)
      placeholder: ex. Été 2023, Décembre 2022, Dernier Noël
    validations:
      required: false

  - type: checkboxes
    id: photo-consent
    attributes:
      label: Consentement de Partage de Photos
      description: Veuillez confirmer que vous avez la permission de partager ces photos
      options:
        - label: Je confirme que j'ai la permission de partager ces photos publiquement sur le site
          required: true
        - label: Ces photos peuvent être affichées dans la galerie familiale
          required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## 📋 Instructions de Téléchargement Rapide :

        **Option 1 : GitHub Issues (cette page)**
        1. **Glissez-déposez** vos photos directement dans la zone "Description des Photos" ci-dessus
        2. Ou **cliquez sur l'icône trombone** pour parcourir et sélectionner les fichiers de votre appareil
        3. Vous pouvez télécharger **plusieurs photos** à la fois (jusqu'à 10 Mo chacune)
        4. Attendez que le téléchargement soit terminé (vous verrez une barre de progression)
        5. Ajoutez des descriptions ou des souvenirs sur les photos
        6. Cliquez sur **"Soumettre une nouvelle issue"** en bas

        **Option 2 : Email (plus facile !)**
        - Envoyez simplement vos photos par email à : **marineeterwan29@gmail.com**
        - Sujet : "Photos pour Marine et Erwan"
        - Incluez votre nom et une brève description

        ---

        ### ✨ Que se passe-t-il ensuite ?

        - Nous recevrons une notification de votre téléchargement
        - Nous examinerons les photos (généralement dans les 1-3 jours)
        - Les photos approuvées seront ajoutées à la section "Partagé par la Famille et les Amis"
        - Vous recevrez un commentaire sur cette issue lorsque vos photos seront en ligne !

        ---

        **Vous rencontrez des difficultés ?** Contactez l'administrateur du site ou laissez un commentaire ci-dessous.

        Merci de nous aider à célébrer Marine et Erwan ! 🎂🎈
